### ISSUE TITLE
mass text?

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corups#2]
hi

Maybe going blind but can't find where mass text is now?....

thanks, Ian

**Comment by nqthqn** [comment]
You could recreate it from these i think: https://github.com/HughP/dnj-corups/tree/master/Mass-Text-files-Before-consolidation

**Comment by nqthqn** [comment]
here it is, https://github.com/HughP/dnj-corups/commit/7f55f53fe0d741fd33850ad7cf3cf374971db7e1#diff-3c681969a0ac8049ec9f851f5bc44639

**Comment by nqthqn** [comment]
Here you go: https://raw.githubusercontent.com/HughP/dnj-corups/7f55f53fe0d741fd33850ad7cf3cf374971db7e1/mass-text.txt

**Comment by HughP** [comment]
That particular mass-text.txt file was missing 4 issues of the newspaper, and the three chapters from the medical book. A new release tonight will bring all that together with a few commands.

**Comment by iandoug** [comment]
On Wednesday, 06 June 2018 1:59:33 AM SAST Nathan Nichols wrote:

> Here you go:
> https://raw.githubusercontent.com/HughP/dnj-corups/7f55f53fe0d741fd33850ad7
> cf3cf374971db7e1/mass-text.txt

Thanks.

There are lines like 

"Nimlʋʋ 001 –'Zë Zë -Kwɛ 2005	

Which are not in the first version you linked to.
However the first character shows up in my browser as a square, and is missing 
in the copy-paste above. So don't know if it's some sort of "tab" character, 
or if my browser is unable to find a fallback character to render it. I'm 
reasonably utf-8 compliant.

How does it look your side?

Might as well attach a screenshot... here :-)

Thanks, Ian

-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273
