### ISSUE TITLE
Latin support

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corups#3]
Re the keys actually needed .... I know you said keyboard should only support Dan, but ...

1. presume some plan needs to be made to support French as well, even if "awkward"?

2. Won't someone please think of the poor programmers?... :-) I noticed that several Latin letters are not used in Dan, and was planning on simply leaving them off, then thought about the Programmers... and said letters may be needed in reserved words in some language ... guess this is variation of the French problem above.

3. Any comments on use or nor of that Pan-African alphabet SIL was working on? Too way-out?

thanks.

**Comment by HughP** [comment]
Re 1. Yes I agree on the French support but I want to know what the layout difference cost will be between a pure Dan, layout and one that includes thoughts about French letters.

I have thought about Internet characters, but not about reserved words like python might have.... presumably though programmers are not going to get their training in Dan, at least not yet... so two keyboard layout will solve that problem, for now. 

 As far as I know the Pan-African layout didn't go anywhwere. you could check here: https://github.com/silnrsi/wsresources/
or here: https://github.com/keymanapp/keyboards

**Comment by iandoug** [comment]
On Wednesday, 06 June 2018 4:02:27 AM SAST HughP wrote:

> Re 1. Yes I agree on the French support but I want to know what the layout
> difference cost will be between a pure Dan, layout and one that includes
> thoughts about French letters.

Found this:

https://secure.tavultesoft.com/keyman/downloads/keyboards/details.php?
KeyboardID=412&FromKeyman=0#

After considerable fun and games, have keyman developer running on Win7 in 
VirtualBox (could not get it to behave under Wine).

However was hoping above link would show me "a" keyboard to use as a starting 
point, but it seems to be some sort of "binary keyboard driver" thing for use 
with Keyman Desktop rather than (Linux-style) a file that you can actually 
edit or play with.

Is there way to "reverse engineer" those distro files? Or must I see if I can 
persuade the desktop version to show me an on-screen keyboard? Saw some option 
along those lines somewhere.

Thanks, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by HughP** [comment]
Your, looking for a .kmn file.

**Comment by iandoug** [comment]
hi

On Thursday, 07 June 2018 3:22:39 AM SAST HughP wrote:

> SIl Panafrica keyboard:
> https://keyman.com/keyboards/africadeadkey

This claims to include the source code but the .kmp file says there is no help 
available ... all I can see is QWERTY, even when I switch language to French.

It won't open in Developer, only Desktop.

Maybe I need to download the .exe and install the whole kaboodle... 

Tried https://help.keyman.com/keyboard/africadeadkey but think that doesn't 
exist anymore ...

ah, this is what we want:

http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=AfricanKeyboard1

Okay, reading the PDF, they say 

To access characters on this chart, just type the key. So, for example, to get 
“â”, type “a” followed by “^”. 
To get “ḗ” type “e” followed by “_”, followed by “/”. 

I'd much rather look at putting something like â on AltGr-a.

Let me get a list of characters and available slots.

I saw something about dh replacing that d with a curved stem (that my char 
picker won't find now). Is this still the game plan, or do we want to replace 
the double letters with a single symbol?

Thanks, Ian

-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by iandoug** [comment]
On Thursday, 07 June 2018 1:01:50 PM SAST Ian Douglas wrote:

> http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=AfricanKeyboard1

see attached :-)

Will revert to KLA instead...

Cheers, Ian

-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by iandoug** [comment]
Translating from the French text in masstext:

1. c, h, j, qu and x do not exist in dan.
2. r is never at the beginning of a word.

But I guess that assertion (1) dates from before they started using h with b and d?

**Comment by HughP** [comment]
Yes, well if they consider <dh> a single "letter" then "h" is not a "letter". The issue here is that there is not a lot of consensus in the orthography industry on what constitutes a letter. I am taking a strong position on a divisive issue. - I'm closing this multitude of issues because I think we I have answered everything. If I haven't then please open a new issue for that specific thing and then reference this issue if needed. use this syntax: `#issuenumber`.
