### ISSUE TITLE
French style quotes

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corups#4]
Hi

Silly github still does not check for zero content before accepting posting ...

Anyway, I suspect you have usage of « and » (and the single versions) swapped around in the readme. ... looking at masstext, it looks like » is used for closing speech rather than opening it.

eg
 «’Ya ! =A 'wɔn ya n -bha -ziaan fiëë -yö -dhö -wa !»

**Comment by nqthqn** [comment]
![screen shot 2018-06-07 at 9 34 17 am](https://user-images.githubusercontent.com/857356/41113252-f979e55e-6a35-11e8-85f1-b6e324134654.png)

**Comment by iandoug** [comment]
@nqthqn try opening new issue, with subject heading, then hit Enter without anything in the text block.

**Comment by HughP** [comment]
Ok thanks, I'll fix it in the read me.

**Comment by HughP** [comment]
Actually I just was reading the orthography description in the 1994 book.

Codepoint   | Grapheme | Usage
-------------|-----|----
U+00BB | »  | les guillemets ouvrant et
U+00AB  | «  | fermant un discourse direct  

It looks like there is authorship errors in the corpus.
